import "../styles/globals.css";
import Header from "@/components/Header/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body className="min-h-screen bg-[#0f172a] text-white flex flex-col">
    <Header/>

    <main className="flex-grow flex overflow-hidden" >
          {children}
        </main>
      </body>
    </html>
  );
}
