import "../styles/globals.css";
import Header from "@/components/Header/Header";
import RecoilRootProvider from "@/components/RecoilRootProvider";
import AuthWrapper from "@/components/AuthWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({children,}: { children: React.ReactNode; }) {
  return (
      <html lang="en">
        <body className="min-h-screen bg-[#0f172a] text-white flex flex-col">
          <RecoilRootProvider>
            <AuthWrapper>
              {children}
            </AuthWrapper>
          </RecoilRootProvider>
        </body>
      </html>
  );
}
